AllCops:
  TargetRubyVersion: 2.5.0
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'exe/*'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/HandleExceptions:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/Sample:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Layout/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StructInheritance:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
